//
// Jon Leininger
// 2-9-25
// Stadium Seating Programming Project
// COSC 1030
//


#include <iostream>
#include <iomanip>
using namespace std;

int main()
{ 
	double classA = 15.0;
	double classB = 12.0;
	double classC = 9.0;

	double classAtickets;
	double classBtickets;
	double classCtickets;
	double total;
	
	cout << "Enter the number of tickets sold for each class " << endl;
	cout << "Class A" << endl;
	cin >> classAtickets;
	cout << "Class B" << endl;
	cin >> classBtickets;
	cout << "Class C" << endl;
	cin >> classCtickets;

	total =   (classAtickets * classA) +
		(classBtickets * classB) +
		(classCtickets * classC);
	
	cout << "The total income generated by ticket sales is " << setprecision(2) << fixed << total << endl;
	
	


	return 0;












}

